### ISSUE TITLE
Dependency issues during build process

### ISSUE THREAD

**Issue by jancborchardt** [mailvelope/mailvelope#306]
So @toberndo I’m about to submit a fix for https://github.com/mailvelope/mailvelope/issues/303, however I have some problems during the build process.

The instructions are awesome (very easy to copy-paste for a half-techie like me ;) but I get some errors. During the Chrome dependency installation `cd dep/chrome/openpgpjs; npm install && grunt`:

```
npm WARN unmet dependency /home/jan/mailvelope/dep/chrome/openpgpjs/node_modules/grunt-mocha-test/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/jan/mailvelope/dep/chrome/openpgpjs/node_modules/grunt-mocha-test/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.0.0
npm WARN unmet dependency /home/jan/mailvelope/dep/chrome/openpgpjs/node_modules/grunt-mocha-test/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/jan/mailvelope/dep/chrome/openpgpjs/node_modules/grunt-mocha-test/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5

/home/jan/mailvelope/dep/chrome/openpgpjs/node_modules/grunt/node_modules/findup-sync/lib/findup-sync.js:33
    }).flatten().uniq().value();
       ^
TypeError: Object Gruntfile.js has no method 'flatten'
    at Object.module.exports [as findup] (/home/jan/mailvelope/dep/chrome/openpgpjs/node_modules/grunt/node_modules/findup-sync/lib/findup-sync.js:33:8)
    at Task.task.init (/home/jan/mailvelope/dep/chrome/openpgpjs/node_modules/grunt/lib/grunt/task.js:427:16)
    at Object.grunt.tasks (/home/jan/mailvelope/dep/chrome/openpgpjs/node_modules/grunt/lib/grunt.js:120:8)
    at Object.module.exports [as cli] (/home/jan/mailvelope/dep/chrome/openpgpjs/node_modules/grunt/lib/grunt/cli.js:38:9)
    at Object.<anonymous> (/usr/lib/node_modules/grunt-cli/bin/grunt:45:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

And during the last step `npm install && bower install && grunt`:

```
npm http GET https://registry.npmjs.org/mimefuncs
npm http 304 https://registry.npmjs.org/mimefuncs
npm WARN unmet dependency /home/jan/mailvelope/node_modules/grunt/node_modules/grunt-legacy-log requires lodash@'~2.4.1' but will load
npm WARN unmet dependency /home/jan/mailvelope/node_modules/grunt/node_modules/lodash,
npm WARN unmet dependency which is version 0.9.2
npm WARN unmet dependency /home/jan/mailvelope/node_modules/grunt-contrib-compress/node_modules/archiver/node_modules/file-utils requires lodash@'~2.1.0' but will load
npm WARN unmet dependency /home/jan/mailvelope/node_modules/grunt-contrib-compress/node_modules/archiver/node_modules/lodash,
npm WARN unmet dependency which is version 2.4.1
Loading "jshint.js" tasks...ERROR
>> Error: Cannot find module 'hooker'
Loading "watch.js" tasks...ERROR
>> Error: Cannot find module 'lodash'
Loading "compress.js" tasks...ERROR
>> Error: Cannot find module 'lodash'
Loading "mozilla_addon_sdk.js" tasks...ERROR
>> Error: Cannot find module 'delayed-stream'
Loading "jscs.js" tasks...ERROR
>> Error: Cannot find module 'vow'
Warning: Task "jshint" not found. Use --force to continue.

Aborted due to warnings.
```

How can I fix that?

**Comment by toberndo** [comment]
@jancborchardt Not sure, maybe a missing dependency in npm. Can you try `npm cache clean` and repeat the process?

**Comment by jancborchardt** [comment]
Yeah – still the same issue.

**Comment by toberndo** [comment]
Lots of updates to dependencies and build process recently. Please re-open if problem still persists.
