### ISSUE TITLE
Error in openpgp.decryptKey

### ISSUE THREAD

**Issue by fujisan43** [mailvelope/mailvelope#556]
When trying to decrypt a mail, I get this error
`Error in openpgp.decryptKey`
after typing the password.

Any idea what is wrong?

**Comment by fujisan43** [comment]
Still facing this error.

**Comment by systemplatine** [comment]
To get the logs you have to open the extensions page in another tab by typing  chrome:extensions  into the address bar.
On the top right of the page enable developer mode. In the Mailvelope entry on the page click on background.html
A new browser window comes up. Ensure that the tab Console is active and add any errors in red to the report.

**Comment by ForeverWintr** [comment]
There is no `background.html` link in the mailvelope entry on my extensions page in developer mode. There is a `background page` link, but no errors appear in the resulting console.

**Comment by fujisan43** [comment]
@ForeverWintr Have you moved your subkey to a yubikey?

**Comment by fujisan43** [comment]
Well, I did. So I generated new keys that I did not move to a smartcard. I Imported them in mailvelope and it worked.

**Comment by ross-at-ormo** [comment]
I have this same issue in both Chrome and Firefox. I have imported my keys from gpg. As per best practice my primary secret key has been removed and is not stored locally on my laptop and I have created a separate signing subkey. When I imported my keys to Mailvelope I imported the export of my public keys and then an export of my private subkeys (which worked fine), therefore the Mailvelope keyring does not contain my primary secret key either. I tried to simply encrypt/decrypt a message addressed to myself using the included "Text Encryption/Decryption" feature. When I decrypt the message, I am prompted for my secret key password which I enter and then I receive the error: 
> Error in openpgp.decryptKey

I checked the Chrome logs, this is what appears in the console:
```
Error in event handler for (unknown): TypeError: Cannot read property 'emit' of undefined
    at DecryptController.dialogCancel (chrome-extension://kajibbejlbohfaggdiogboambcijhkke/background.bundle.js:25429:23)
    at DecryptController.handlePortMessage (chrome-extension://kajibbejlbohfaggdiogboambcijhkke/background.bundle.js:27970:17)
```
I don't really understand what the issue is, since I am not signing anything, just encrypting which should therefore only rely on the encryption subkey which was automatically generated when I created my keys. Just for the sake of completeness I copied the encrypted message and saved it as a file which I can decrypt just fine using gpg --decrypt.

Hopefully this helps

**Comment by stdedos** [comment]
Same issue for me. I have been using the extension "normally" before the updates (so I think https://github.com/mailvelope/mailvelope/issues/544#issuecomment-337395612 does not apply).

I am also able to use everything normally on Ubuntu Bionic.

Chrome 78 over Win 10

```
GPGME is not available. CONN_TIMEOUT
09:15:38.218 keys.mailvelope.com/api/v1/key?email=noreply%40facebookmail.com:1 Failed to load resource: the server responded with a status of 404 (Not Found)
09:15:39.668 list-types.js:1 WKD: Did not find key (Errors are expected): Error: WKD: Failed to parse result for 'noreply@facebookmail.com': Error: Error during parsing. This message / key probably does not conform to a valid OpenPGP format.
09:15:46.218 list-types.js:1 getPgpBackend().decrypt() error Error: Error in openpgp.decryptKey. Error decrypting private key: key.keyPacket.decrypt is not a function
    at pwdCache_unlockKey (list-types.js:1)
09:42:35.307 keys.mailvelope.com/api/v1/key?email=noreply%40facebookmail.com:1 Failed to load resource: the server responded with a status of 404 (Not Found)
09:42:36.274 list-types.js:1 WKD: Did not find key (Errors are expected): Error: WKD: Failed to parse result for 'noreply@facebookmail.com': Error: Error during parsing. This message / key probably does not conform to a valid OpenPGP format.
09:42:44.050 list-types.js:1 getPgpBackend().decrypt() error Error: Error in openpgp.decryptKey. Error decrypting private key: key.keyPacket.decrypt is not a function
    at pwdCache_unlockKey (list-types.js:1)
00:17:38.182 keys.mailvelope.com/api/v1/key?email=noreply%40facebookmail.com:1 Failed to load resource: the server responded with a status of 404 (Not Found)
00:17:39.554 list-types.js:1 WKD: Did not find key (Errors are expected): Error: WKD: Failed to parse result for 'noreply@facebookmail.com': Error: Error during parsing. This message / key probably does not conform to a valid OpenPGP format.
00:17:44.894 list-types.js:1 getPgpBackend().decrypt() error Error: Error in openpgp.decryptKey. Error decrypting private key: key.keyPacket.decrypt is not a function
    at pwdCache_unlockKey (list-types.js:1)
```

**Comment by larsonmars** [comment]
I have found a simple work around, you can change in the mailvelope security settings to have decrypted messages displayed in a separate window created by mailvelope (see screenshot, sorry its German, but you should be able to map it to your language).

![grafik](https://user-images.githubusercontent.com/33299122/82116190-20bef580-9768-11ea-9b44-b04e5f7d5358.png)

**Comment by AnastasiosT** [comment]
I'm facing the same issue. I moved my key to my yubikey.
